version: '3.9'
services:
  app:
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
        NEXT_PUBLIC_BUCKET_API_KEY: ${NEXT_PUBLIC_BUCKET_API_KEY}
        NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
    working_dir: /app
    ports:
      - '3000:3000'
    image: t3-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - S_MAXAGE=${S_MAXAGE}
      - URL_EXPIRATION_TIME=${URL_EXPIRATION_TIME}
      - BUCKET_CORS_EXPIRATION_TIME=${BUCKET_CORS_EXPIRATION_TIME}
      - REDIS_URL=${REDIS_URL}
