name: 'Auto Assign'
on:
  pull_request:
    types: [labeled]

jobs:
  assign-reviewer-assignee:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.label.name == 'BE' }}
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto_assign_be_config.yml'
          repo-token: ${{ secrets.WORKFLOW_TOKEN }}
      - if: ${{ github.event.label.name == 'FE' }}
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto_assign_fe_config.yml'
          repo-token: ${{ secrets.WORKFLOW_TOKEN }}
